//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::entities::BlockState;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "block")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub chain_id: String,
    pub block_number: i64,
    pub block_hash: String,
    pub parent_hash: String,
    pub transaction_count: i64,
    pub extrinsic_count: i64,
    pub state: BlockState,
    pub mined_at: Option<TimeDateTimeWithTimeZone>,
    pub finalized_at: Option<TimeDateTimeWithTimeZone>,
    pub created_at: Option<TimeDateTimeWithTimeZone>,
    pub updated_at: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
