//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::entities::LockReason;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "locked_asset")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub class_id: i64,
    pub contract_id: i64,
    pub chain_id: String,
    pub asset_id: String,
    pub address: String,
    pub delegate: String,
    pub nonce: String,
    pub value: String,
    pub lock_reason: LockReason,
    pub expires_at: i64,
    pub created_at: Option<TimeDateTimeWithTimeZone>,
    pub updated_at: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
