//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::asset::Entity as Asset;
pub use super::block::Entity as Block;
pub use super::class::Entity as Class;
pub use super::contract::Entity as Contract;
pub use super::extrinsic::Entity as Extrinsic;
pub use super::locked_asset::Entity as LockedAsset;
pub use super::transaction::Entity as Transaction;
